apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaraon
spec:
  selector:
    matchLabels:
      app: jaraon
  replicas: 1
  template:
    metadata:
      labels:
        app: jaraon
    spec:
      containers:
      - name: jaraon
        image: okteto.dev/jaraon:latest
        ports:
        - containerPort: 8080
